changing monspec validation to do a pullcompare instead of pushcompare and validate results in the concourse task

diff --git a/ci/tasks/validate-via-monspec b/ci/tasks/validate-via-monspec
--- a/ci/tasks/validate-via-monspec
+++ b/ci/tasks/validate-via-monspec
@@ -14,4 +14,17 @@ eval monspeccomparison=$monspeccomparison
 echo "Validating load test results via monspec comparison $monspeccomparison after 60s wait"
 sleep 60
 
-python /dtcli/dtcli.py monspec pushcompare ./PivotalDevOpsTutorial/ci/smplmonspec.json ./PivotalDevOpsTutorial/ci/smplpipelineinfo.json $monspeccomparison 60
+# disabling pushcompare as it doesn't create problems anyways
+#python /dtcli/dtcli.py monspec pushcompare ./PivotalDevOpsTutorial/ci/smplmonspec.json ./PivotalDevOpsTutorial/ci/smplpipelineinfo.json $monspeccomparison 60 > monspecpullcompare.json
+
+# fetching monspec comparison results, pretty-printing them, then failing if totalViolations > 0 via POSIX compliant logic for portability
+python /dtcli/dtcli.py monspec pullcompare ./PivotalDevOpsTutorial/ci/smplmonspec.json ./PivotalDevOpsTutorial/ci/smplpipelineinfo.json $monspeccomparison 60 > monspecpullcompare.json
+jq '.' monspecpullcompare.json
+totalViolations="$(jq -r '.totalViolations' monspecpullcompare.json)"
+if [ $totalViolations -gt 0 ]; then
+echo "We encountered $totalViolations monspec violations, failing build"
+exit 1
+else 
+echo "No monspec violations encountered"
+exit 0
+fi
